#!/bin/bash

xsetroot -cursor_name left_ptr
picom &
sxhkd &
setxkbmap -layout us,ru -option grp:ctrl_space_toggle &
feh --bg-fill $HOME/Pictures/background.png &
polybar &

bspc config border_width        3
bspc config window_gap          15

bspc config focused_border_color '#c0aac8'
bspc config normal_border_color '#795968'

bspc config split_ratio         0.62
bspc config focus_follows_pointer       true
bspc config pointer_modifier    mod1

bspc config automatic_scheme    spiral
